import type { Metadata } from "next";
import './globals.css';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar2';
import Providers from '@/Providers';
import SessionProvider from '@/utils/SessionProvider';

// #region Functions (1)

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <Navbar />
            <Providers>
            {children}
            </Providers>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}

// #endregion Functions (1)

// #region Variables (2)

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// #endregion Variables (2)
